"""FastAPI application entrypoint.

The vector store, embedding model and Ollama client are all initialised in the
lifespan handler, i.e. once when the process starts, and attached to app.state.
Routes read them from there.
"""

from __future__ import annotations

import logging
import sys
from contextlib import asynccontextmanager
from pathlib import Path

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

# Make the repository root importable so `rag_core` resolves whether the app is
# run from backend/ (uvicorn app.main:app) or from the repository root.
REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from app.api.routes import query as query_routes  # noqa: E402
from app.core.config import get_settings  # noqa: E402
from app.services.generation import GenerationService  # noqa: E402
from app.services.retrieval import RetrievalService  # noqa: E402
from app.utils.logging_config import configure_logging  # noqa: E402

logger = logging.getLogger(__name__)


@asynccontextmanager
async def lifespan(app: FastAPI):
    settings = get_settings()
    configure_logging(settings.log_level)
    logger.info("starting %s v%s", settings.app_name, settings.app_version)

    retrieval = RetrievalService(
        vector_store_dir=settings.vector_store_dir,
        embedding_model=settings.embedding_model,
        min_score=settings.min_score,
    )
    generation = GenerationService(
        host=settings.ollama_host,
        model=settings.ollama_model,
        timeout=settings.ollama_timeout,
        temperature=settings.temperature,
    )

    # A missing vector store must not crash the process: /health should still
    # answer and tell the operator exactly what is wrong.
    try:
        retrieval.load()
    except Exception as exc:  # noqa: BLE001
        logger.error("could not load vector store: %s", exc)

    try:
        generation.load()
    except Exception as exc:  # noqa: BLE001
        logger.error("could not configure Ollama client: %s", exc)

    app.state.retrieval = retrieval
    app.state.generation = generation

    yield

    logger.info("shutting down")


def create_app() -> FastAPI:
    settings = get_settings()

    app = FastAPI(
        title=settings.app_name,
        version=settings.app_version,
        description=(
            "Retrieval-Augmented Generation over a local document collection. "
            "Answers are generated by a local Ollama model and grounded in "
            "retrieved passages, with citations."
        ),
        lifespan=lifespan,
    )

    app.add_middleware(
        CORSMiddleware,
        allow_origins=settings.cors_origin_list,
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    app.include_router(query_routes.router)
    return app


app = create_app()
